version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nutthapong10
      MYSQL_DATABASE: nodejsmysql
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
    networks:
      - my_network

  node:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: nutthapong10
      DB_NAME: nodejsmysql
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge
